import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Rishabh Sharma',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/puma.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
      },
       {
      name: 'Harsh Govil',
      email: 'admin1@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Lee',
        logo: '/images/lee.png',
        description: 'best seller',
        rating: 4.2,
        numReviews: 58,
      },
    },
    {
      name: 'Samaksh Tak',
      email: 'admin2@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Adidas',
        logo: '/images/adidas',
        description: 'best seller',
        rating: 4.0,
        numReviews: 100,
      },
      },
      {
      name: 'Shishir Mishra',
      email: 'admin4@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'lenovo',
        logo: '/images/lenovo.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 122,
      },
      },
      {
      name: 'Jeet Patel',
      email: 'admin5@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Apple',
        logo: '/images/apple.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 139,
      },
    },
    {
      name: 'Rishabh Sharma1',
      email: 'admin6@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Redmi',
        logo: '/images/mi.png',
        description: 'best seller',
        rating: 4.6,
        numReviews: 150,
      },
    },
    {
      name: 'Harsh Govil1',
      email: 'admin8@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Patanjali',
        logo: '/images/patanjali.jpg',
        description: 'best seller',
        rating: 4.7,
        numReviews: 143,
      },
    },
    {
      name: 'Robert Govil',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
    {
      name: 'Jeet Patel1',
      email: 'admin9@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Asus',
        logo: '/images/asus.jpg',
        description: 'best seller',
        rating: 4.1,
        numReviews: 180,
      },
    },
    {
      name: 'Jeet Patel2',
      email: 'admin10@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'One-Plus',
        logo: '/images/OnePlus-Logo.png',
        description: 'best seller',
        rating: 4.2,
        numReviews: 300,
      },
    },
    {
      name: 'Jeet Patel3',
      email: 'admin11@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Penguin Publishers',
        logo: '/images/penguin.jpg',
        description: 'best seller',
        rating: 4.8,
        numReviews: 90,
      },
    },
    {
      name: 'Jeet Patel4',
      email: 'admin12@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Philips',
        logo: '/images/philips.jpg',
        description: 'best seller',
        rating: 4.0,
        numReviews: 145,
      },
    },
    {
      name: 'Jeet Patel5',
      email: 'admin13@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Cadbury',
        logo: '/images/cadburylogo.jpg',
        description: 'best seller',
        rating: 4.3,
        numReviews: 90,
      },
    },
    {
      name: 'Jeet Patel6',
      email: 'admin14@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Milton',
        logo: '/images/miltonlogo.jpg',
        description: 'best seller',
        rating: 4.0,
        numReviews: 35,
      },
    },
    {
      name: 'Jeet Patel6',
      email: 'admin15@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Jockey',
        logo: '/images/Jockey-Logo.jpg',
        description: 'best seller',
        rating: 4.6,
        numReviews: 900,
      },
    },
    {
      name: 'Jeet Patel7',
      email: 'admin16@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Axe',
        logo: '/images/axe-logo.jpg',
        description: 'best seller',
        rating: 4.6,
        numReviews: 423,
      },
    },
    {
      name: 'Jeet Patel8',
      email: 'admin17@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Rolex',
        logo: '/images/rolexlogo.jpg',
        description: 'best seller',
        rating: 4.9,
        numReviews: 69,
      },
    },
    {
      name: 'Jeet Patel9',
      email: 'admin18@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Realme',
        logo: '/images/realmelogo.jpg',
        description: 'best seller',
        rating: 4.4,
        numReviews: 435,
      },
    },
  ],
  products: [
    {
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Lenovo Ideapad',
      category: 'Electronics',
      image: '/images/lenovoideapad.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Lenovo',
      rating: 4.5,
      numReviews: 16,
      description: 'Laptop 8gb ram',
    },
    {
      name: 'Macbook Pro',
      category: 'Electronics',
      image: '/images/macbook-pro.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Realme-1',
      category: 'Electronics',
      image: '/images/realme-1-.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Realme',
      rating: 4.5,
      numReviews: 15,
      description: '128gb-mobile-phone',
    },
    {
      name: 'Thinkpad',
      category: 'Electronics',
      image: '/images/thinkpad.jpg',
      price: 50000,
      countInStock: 22,
      brand: 'lenovo',
      rating: 4.4,
      numReviews: 15,
      description: 'Intel Core i5 Gen 8 , 12.6 inches , fingerprint lock',
    },
    {
      name: 'Vivobook',
      category: 'Electronics',
      image: '/images/vivobook.jpg',
      price: 50000,
      countInStock: 100,
      brand: 'Asus',
      rating: 4.8,
      numReviews: 15,
      description: 'Value for money',
    },
    {
      name: 'Redmi Note 9 Pro',
      category: 'Electronics',
      image: '/images/note9.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Redmi',
      rating: 4.5,
      numReviews: 10,
      description: 'excellent camera',
    },
    {
      name: 'One-Plus Nord',
      category: 'Electronics',
      image: '/images/nord.jpg',
      price: 35000,
      countInStock: 10,
      brand: 'One-Plus',
      rating: 4.5,
      numReviews: 10,
      description: 'Cheapest premium smartphone',
    },
    {
      name: 'Harry Potter and the Half Blood Prince',
      category: 'Books',
      image: '/images/harry.jpg',
      price: 999,
      countInStock: 100,
      brand: 'Penguin Publishers',
      rating: 4.9,
      numReviews: 158,
      description: 'One of the best written books',
    },
    {
      name: 'Philips Trimmer',
      category: 'Electronics',
      image: '/images/trimmer.jpg',
      price: 2000,
      countInStock: 500,
      brand: 'Philips',
      rating: 3.8,
      numReviews: 48,
      description: 'Trim with style',
    },
    {
      name: 'Patanjali Dantkanti',
      category: 'Everyday Essentials',
      image: '/images/dantkanti.jpg',
      price: 100,
      countInStock: 500,
      brand: 'Patanjali',
      rating: 4.9,
      numReviews: 48,
      description: 'Made in India',
    },
    {
      name: 'Dairy Milk Silk',
      category: 'Sweets',
      image: '/images/cadbury.jpg',
      price: 150,
      countInStock: 500,
      brand: 'Cadburry',
      rating: 4.9,
      numReviews: 48,
      description: 'Kuch meetha ho jaye',
    },
    {
      name: 'Milton water bottle',
      category: 'Everyday Essentials',
      image: '/images/milton.jpg',
      price: 1000,
      countInStock: 100,
      brand: 'Milton',
      rating: 4.9,
      numReviews: 48,
      description: 'Jal hai to jeevan hai',
    },
    {
      name: 'Jockey inner wear',
      category: 'Everyday Essentials',
      image: '/images/jockey.jpg',
      price: 300,
      countInStock: 100,
      brand: 'Jockey',
      rating: 4.4,
      numReviews: 16,
      description: 'Bade Araam se',
    },
    {
      name: 'Axe Deo',
      category: 'Everyday Essentials',
      image: '/images/axe.jpg',
      price: 250,
      countInStock: 100,
      brand: 'Axe',
      rating: 4.7,
      numReviews: 16,
      description: 'Body deodarant',
    },
    {
      name: 'JAEGER-LECOULTRE',
      category: 'Watches',
      image: '/images/jlc-rolex.jpg',
      price: 830000,
      countInStock: 5,
      brand: 'Rolex',
      rating: 5,
      numReviews: 2,
      description: 'The signature watch',
    },
  ],
};
export default data;